### ISSUE TITLE
HTML in Cards

### ISSUE THREAD

**Issue by pintman** [pyscript/pypercard#11]
It would be great to be able to format text in the 'text' attribute. Maybe even complexer structures like tables would become useful. Is it possible to enter html-Blocks into the text-attribute and render it?

**Comment by ntoll** [comment]
@pintman closing this issue, since we're re-writing PyperCard in PyScript, making (underneath) the default UI  specification language as HTML. 😄

**Comment by pintman** [comment]
Sounds great. 😀
