### ISSUE TITLE
text attribute not updated when staying on card

### ISSUE THREAD

**Issue by pintman** [pyscript/pypercard#12]
I like to update a card's text value but like to stay on it. Although a transition function is evaluated and the data_store attributes changed, the text value does not. The following code should clarify the problem.

Hitting the update button does not change the counter value in the text.

```
from pypercard import Card, CardApp

def update(data_store, form_value):
    data_store['counter'] += 1
    print('counter value', data_store['counter'])
    return 'main'

stack = [
    Card('main',
        text='Counter: {counter}',
        buttons=[{'label':'Update', 'target':update}])
]
app = CardApp(stack=stack, data_store={'counter': 0})
app.run()

```

**Comment by ntoll** [comment]
@pintman hey hey... yup. This is a known problem which will be fixed in the next release (having been discovered by an 11yo coder just a couple of weeks ago in a workshop I was running). Thanks for the report, I'll make sure this issue is closed/mentioned when the fix lands in the release.

**Comment by ntoll** [comment]
Closing since this will be fixed in the first (PyScript) based version PyperCard.
