### ISSUE TITLE
Empty window when using mu-editor (alpha) on some Debian 10 installations  

### ISSUE THREAD

**Issue by sudofrank** [pyscript/pypercard#14]
The code below fails for me when run from mu-editor (alpha) but <i>not</i> when run from the command line. I'm on Debian 10 but the issue is clearly something to do with my specific installation as it works fine (through mu) on another Debian 10 machine we've tested on. 

The failure mode is a transparent window - only the frame is rendered, with the desktop visible through it. There are no error messages in the mu console log. If I move the frame, the original image of the desktop behind moves with it. Implementing #13 would no doubt help massively to resolve this issue.
<pre><code>from pypercard import Card, CardApp, Inputs

my_cards = [
    Card("textbox-test",
        text="MY TEXTBOX",
        form=Inputs.TEXTBOX
        )
]

app = CardApp(stack=my_cards)
app.run()</code></pre>

**Comment by arthomnix** [comment]
If it works when you run it from the terminal, isn't this more of a Mu problem?
PyperCard works fine for me on Debian 10.

**Comment by ntoll** [comment]
Hi, closing this issue since PyperCard is being written on-top of PyScript (i.e. the rendering is done in a browser context...).
