### ISSUE TITLE
Predefined values for forms

### ISSUE THREAD

**Issue by sudofrank** [pyscript/pypercard#16]
It would be useful to be able to define a value for TEXTBOX, TEXTAREA and SLIDER forms that they take when they're initialised. In the case of TEXT* forms this would allow for some pre-existing text string to be edited, or copied out of the form.

**Comment by ntoll** [comment]
This is already an aspect of the re-write of PyperCard in PyScript. :+1: Closing. New release coming within weeks. 😉
