### ISSUE TITLE
Need distribution dependenceis listed for installation

### ISSUE THREAD

**Issue by kushaldas** [pyscript/pypercard#17]
When installing `pypercard` on a new system, we should also mention all the system package based dependencies. Asking this particular as I spent the last 30 minutes to figure out all the dependencies on Debian Buster.

**Comment by kushaldas** [comment]
Kivy is the main culprit here, figuring out the dependencies was difficult.

**Comment by ntoll** [comment]
@kushaldas :-( I'm so sorry. AFAICT, `pip` installing it all in a venv should be all that's required. What's missing WRT Debian Buster?

**Comment by kushaldas** [comment]
@ntoll Dependencies to build ``Kivy``.

**Comment by rjw57** [comment]
On stretch, all I needed was libgl1-mesa-dev and python3-dev.

**Comment by knowingpark** [comment]
Hi, 
I didn't have pygame installed! 
(I'm not sure if this is the right place to write this)
LMDE 4 Debbbie

**Comment by ntoll** [comment]
Closing this since we're re-writing PyperCard on top of PyScript. Kivy be gone. 🙂
