### ISSUE TITLE
Pypercard requires Python 3.6 or greater

### ISSUE THREAD

**Issue by rjw57** [pyscript/pypercard#18]
On Debian stretch, the system Python is python 3.5. Unfortunately the use of f-strings means that pypercard is incompatible with Python 3.5.

Adding `python_requires='>3.5'` or similar to `setup.py` would, with later setuptools, prevent installation on unsupported Python versions.

**Comment by ntoll** [comment]
We're re-writing PyperCard to use PyScript (so Python is run in a browser context for rendering things). Ergo, the Python version is specified via PyScript and this problem will no longer be an issue. :+1:
