### ISSUE TITLE
Allow image sprite adding and clicking on them

### ISSUE THREAD

**Issue by kushaldas** [pyscript/pypercard#7]
As a normal desktop user, I would love to add some images to a location in the card, and then click on them to move to another card.

**Comment by ntoll** [comment]
@kushaldas what a great idea. How about we borrow the location scheme for placing the images from the "compass points" suggestion in #5 (e.g. you'd be saying you want such and such an image in the NW of the screen or along (S, SW) areas of the screen. Then the image placement would match the tap points. :-)

**Comment by kushaldas** [comment]
@ntoll This sounds good, just add a few more locations :)

**Comment by ntoll** [comment]
So, remember this is beginner focused... and a complicated positioning system would put folks off. In the tap issue (#5) I suggest nine possible locations named after the compass points:

```
NW  N  NE
 W  C  E
SW  S  SE
```

(Where C is "centre".)

If we allow arbitrary placement, I think we'd be opening a complicated and messy can of worms. I'm anxious to start (and as much as possible keep things) simple.

Does that make sense? Would love feedback!

**Comment by kushaldas** [comment]
These 9 positions are good enough to have.

**Comment by ntoll** [comment]
Cool... if folks need anything more complicated / flexible, we'll soon find out (and whatever we respond with will be based upon user feedback rather than guess work). ;-)

User focused development, FTW.

**Comment by ntoll** [comment]
Closing this since we're re-writing PyperCard to use PyScript and the underlying UI framework works very differently (i.e. it's just going to be POSH [plain old semantic HTML]). So, if the `<img id="foo"/>` is clicked, some transition will kick in. ;-)
